In [6]:
import pandas as pd

In [7]:
data2 = pd.read_csv('cust.csv')

In [8]:
data2

,cust_id,customer_name,segment,age,country,city,state,postal_code,region
0,cust_id-CG-12520,Claire Gute,Consumer,67,United States,Henderson,Kentucky,42420,South
1,cust_id-DV-13045,Darrin Van Huff,Corporate,31,United States,Los Angeles,California,90036,West
2,cust_id-SO-20335,Sean O'Donnell,Consumer,65,United States,Fort Lauderdale,Florida,33311,South
3,cust_id-BH-11710,Brosina Hoffman,Consumer,20,United States,Los Angeles,California,90032,West
4,cust_id-AA-10480,Andrew Allen,Consumer,50,United States,Concord,North Carolina,28027,South
5,cust_id-IM-15070,Irene Maddox,Consumer,66,United States,Seattle,Washington,98103,West
6,cust_id-HP-14815,Harold Pawlan,Home Office,20,United States,Fort Worth,Texas,76106,Central
7,cust_id-PK-19075,Pete Kriz,Consumer,46,United States,Madison,Wisconsin,53711,Central
8,cust_id-AG-10270,Alejandro Grove,Consumer,18,United States,West Jordan,Utah,84084,West
9,cust_id-ZD-21925,Zuschuss Donatelli,Consumer,66,United States,San Francisco,California,94109,West
10,cust_id-KB-16585,Ken Black,Corporate,67,United States,Fremont,Nebraska,68025,Central
11,cust_id-SF-20065,Sandra Flanagan,Consumer,41,United States,Philadelphia,Pennsylvania,19140,East
12,cust_id-EB-13870,Emily Burns,Consumer,34,United States,Orem,Utah,84057,West
13,cust_id-EH-13945,Eric Hoffmann,Consumer,21,United States,Los Angeles,California,90049,West
14,cust_id-TB-21520,Tracy Blumstein,Consumer,48,United States,Philadelphia,Pennsylvania,19140,East
15,cust_id-MA-17560,Matt Abelman,Home Office,19,United States,Houston,Texas,77095,Central
16,cust_id-GH-14485,Gene Hale,Corporate,28,United States,Richardson,Texas,75080,Central
17,cust_id-SN-20710,Steve Nguyen,Home Office,46,United States,Houston,Texas,77041,Central
18,cust_id-LC-16930,Linda Cazamias,Corporate,31,United States,Naperville,Illinois,60540,Central
19,cust_id-RA-19885,Ruben Ausman,Corporate,51,United States,Los Angeles,California,90049,West
20,cust_id-ES-14080,Erin Smith,Corporate,20,United States,Melbourne,Florida,32935,South
21,cust_id-ON-18715,Odella Nelson,Corporate,27,United States,Eagan,Minnesota,55122,Central
22,cust_id-PO-18865,Patrick O'Donnell,Consumer,64,United States,Westland,Michigan,48185,Central
23,cust_id-LH-16900,Lena Hernandez,Consumer,66,United States,Dover,Delaware,19901,East
24,cust_id-DP-13000,Darren Powers,Consumer,40,United States,New Albany,Indiana,47150,Central
25,cust_id-JM-15265,Janet Molinari,Corporate,23,United States,New York City,New York,10024,East
26,cust_id-TB-21055,Ted Butterfield,Consumer,34,United States,Troy,New York,12180,East
27,cust_id-KM-16720,Kunst Miller,Consumer,69,United States,Los Angeles,California,90004,West
28,cust_id-PS-18970,Paul Stevenson,Home Office,31,United States,Chicago,Illinois,60610,Central
29,cust_id-BS-11590,Brendan Sweed,Corporate,45,United States,Gilbert,Arizona,85234,West
30,cust_id-KD-16270,Karen Daniels,Consumer,59,United States,Springfield,Virginia,22153,South
31,cust_id-HM-14980,Henry MacAllister,Consumer,35,United States,New York City,New York,10009,East
32,cust_id-JE-15745,Joel Eaton,Consumer,25,United States,Memphis,Tennessee,38109,South
33,cust_id-KB-16600,Ken Brennan,Corporate,29,United States,Houston,Texas,77041,Central
34,cust_id-SC-20770,Stewart Carmichael,Corporate,18,United States,Decatur,Alabama,35601,South
35,cust_id-DN-13690,Duane Noonan,Consumer,42,United States,San Francisco,California,94122,West
36,cust_id-JC-16105,Julie Creighton,Corporate,56,United States,Durham,North Carolina,27707,South
37,cust_id-CS-12400,Christopher Schild,Home Office,33,United States,Chicago,Illinois,60623,Central
38,cust_id-PG-18895,Paul Gonzalez,Consumer,64,United States,Rochester,Minnesota,55901,Central
39,cust_id-GM-14455,Gary Mitchum,Home Office,64,United States,Houston,Texas,77095,Central
40,cust_id-JS-15685,Jim Sink,Corporate,33,United States,Los Angeles,California,90036,West
41,cust_id-KB-16315,Karl Braun,Consumer,70,United States,Minneapolis,Minnesota,55407,Central
42,cust_id-RB-19705,Roger Barcio,Home Office,63,United States,Portland,Oregon,97206,West
43,cust_id-PN-18775,Parhena Norris,Home Office,35,United States,New York City,New York,10009,East
44,cust_id-KD-16345,Katherine Ducich,Consumer,33,United States,San Francisco,California,94122,West
45,cust_id-ER-13855,Elpida Rittenbach,Corporate,56,United States,Saint Paul,Minnesota,55106,Central
46,cust_id-RB-19465,Rick Bensley,Home Office,18,United States,Chicago,Illinois,60610,Central
47,cust_id-GZ-14470,Gary Zandusky,Consumer,64,United States,Rochester,Minnesota,55901,Central
48,cust_id-LC-16870,Lena Cacioppo,Consumer,63,United States,Aurora,Colorado,80013,West

In [9]:
data2.head

<bound method NDFrame.head of              cust_id       customer_name      segment  age        country  \
0   cust_id-CG-12520         Claire Gute     Consumer   67  United States
1   cust_id-DV-13045     Darrin Van Huff    Corporate   31  United States
2   cust_id-SO-20335      Sean O'Donnell     Consumer   65  United States
3   cust_id-BH-11710     Brosina Hoffman     Consumer   20  United States
4   cust_id-AA-10480        Andrew Allen     Consumer   50  United States
5   cust_id-IM-15070        Irene Maddox     Consumer   66  United States
6   cust_id-HP-14815       Harold Pawlan  Home Office   20  United States
7   cust_id-PK-19075           Pete Kriz     Consumer   46  United States
8   cust_id-AG-10270     Alejandro Grove     Consumer   18  United States
9   cust_id-ZD-21925  Zuschuss Donatelli     Consumer   66  United States
10  cust_id-KB-16585           Ken Black    Corporate   67  United States
11  cust_id-SF-20065     Sandra Flanagan     Consumer   41  United States
12  cust_id-EB-13870         Emily Burns     Consumer   34  United States
13  cust_id-EH-13945       Eric Hoffmann     Consumer   21  United States
14  cust_id-TB-21520     Tracy Blumstein     Consumer   48  United States
15  cust_id-MA-17560        Matt Abelman  Home Office   19  United States
16  cust_id-GH-14485           Gene Hale    Corporate   28  United States
17  cust_id-SN-20710        Steve Nguyen  Home Office   46  United States
18  cust_id-LC-16930      Linda Cazamias    Corporate   31  United States
19  cust_id-RA-19885        Ruben Ausman    Corporate   51  United States
20  cust_id-ES-14080          Erin Smith    Corporate   20  United States
21  cust_id-ON-18715       Odella Nelson    Corporate   27  United States
22  cust_id-PO-18865   Patrick O'Donnell     Consumer   64  United States
23  cust_id-LH-16900      Lena Hernandez     Consumer   66  United States
24  cust_id-DP-13000       Darren Powers     Consumer   40  United States
25  cust_id-JM-15265      Janet Molinari    Corporate   23  United States
26  cust_id-TB-21055     Ted Butterfield     Consumer   34  United States
27  cust_id-KM-16720        Kunst Miller     Consumer   69  United States
28  cust_id-PS-18970      Paul Stevenson  Home Office   31  United States
29  cust_id-BS-11590       Brendan Sweed    Corporate   45  United States
30  cust_id-KD-16270       Karen Daniels     Consumer   59  United States
31  cust_id-HM-14980   Henry MacAllister     Consumer   35  United States
32  cust_id-JE-15745          Joel Eaton     Consumer   25  United States
33  cust_id-KB-16600         Ken Brennan    Corporate   29  United States
34  cust_id-SC-20770  Stewart Carmichael    Corporate   18  United States
35  cust_id-DN-13690        Duane Noonan     Consumer   42  United States
36  cust_id-JC-16105     Julie Creighton    Corporate   56  United States
37  cust_id-CS-12400  Christopher Schild  Home Office   33  United States
38  cust_id-PG-18895       Paul Gonzalez     Consumer   64  United States
39  cust_id-GM-14455        Gary Mitchum  Home Office   64  United States
40  cust_id-JS-15685            Jim Sink    Corporate   33  United States
41  cust_id-KB-16315          Karl Braun     Consumer   70  United States
42  cust_id-RB-19705        Roger Barcio  Home Office   63  United States
43  cust_id-PN-18775      Parhena Norris  Home Office   35  United States
44  cust_id-KD-16345    Katherine Ducich     Consumer   33  United States
45  cust_id-ER-13855   Elpida Rittenbach    Corporate   56  United States
46  cust_id-RB-19465        Rick Bensley  Home Office   18  United States
47  cust_id-GZ-14470       Gary Zandusky     Consumer   64  United States
48  cust_id-LC-16870       Lena Cacioppo     Consumer   63  United States

               city           state  postal_code   region
0         Henderson        Kentucky        42420    South
1       Los Angeles      California        90036     West
2   Fort Lauderdale         Florida        33311    South
3       Los Angeles      California        90032     West
4           Concord  North Carolina        28027    South
5           Seattle      Washington        98103     West
6        Fort Worth           Texas        76106  Central
7           Madison       Wisconsin        53711  Central
8       West Jordan            Utah        84084     West
9     San Francisco      California        94109     West
10          Fremont        Nebraska        68025  Central
11     Philadelphia    Pennsylvania        19140     East
12             Orem            Utah        84057     West
13      Los Angeles      California        90049     West
14     Philadelphia    Pennsylvania        19140     East
15          Houston           Texas        77095  Central
16       Richardson           Texas        75080  Central
17          Houston           Texas        77041  Central
18       Naperville        Illinois        60540  Central
19      Los Angeles      California        90049     West
20        Melbourne         Florida        32935    South
21            Eagan       Minnesota        55122  Central
22         Westland        Michigan        48185  Central
23            Dover        Delaware        19901     East
24       New Albany         Indiana        47150  Central
25    New York City        New York        10024     East
26             Troy        New York        12180     East
27      Los Angeles      California        90004     West
28          Chicago        Illinois        60610  Central
29          Gilbert         Arizona        85234     West
30      Springfield        Virginia        22153    South
31    New York City        New York        10009     East
32          Memphis       Tennessee        38109    South
33          Houston           Texas        77041  Central
34          Decatur         Alabama        35601    South
35    San Francisco      California        94122     West
36           Durham  North Carolina        27707    South
37          Chicago        Illinois        60623  Central
38        Rochester       Minnesota        55901  Central
39          Houston           Texas        77095  Central
40      Los Angeles      California        90036     West
41      Minneapolis       Minnesota        55407  Central
42         Portland          Oregon        97206     West
43    New York City        New York        10009     East
44    San Francisco      California        94122     West
45       Saint Paul       Minnesota        55106  Central
46          Chicago        Illinois        60610  Central
47        Rochester       Minnesota        55901  Central
48           Aurora        Colorado        80013     West  >

In [12]:
cdata = pd.read_csv('cust.csv',header=0,index_col=0)

In [13]:
cdata

,customer_name,segment,age,country,city,state,postal_code,region
cust_id,,,,,,,,
cust_id-CG-12520,Claire Gute,Consumer,67,United States,Henderson,Kentucky,42420,South
cust_id-DV-13045,Darrin Van Huff,Corporate,31,United States,Los Angeles,California,90036,West
cust_id-SO-20335,Sean O'Donnell,Consumer,65,United States,Fort Lauderdale,Florida,33311,South
cust_id-BH-11710,Brosina Hoffman,Consumer,20,United States,Los Angeles,California,90032,West
cust_id-AA-10480,Andrew Allen,Consumer,50,United States,Concord,North Carolina,28027,South
cust_id-IM-15070,Irene Maddox,Consumer,66,United States,Seattle,Washington,98103,West
cust_id-HP-14815,Harold Pawlan,Home Office,20,United States,Fort Worth,Texas,76106,Central
cust_id-PK-19075,Pete Kriz,Consumer,46,United States,Madison,Wisconsin,53711,Central
cust_id-AG-10270,Alejandro Grove,Consumer,18,United States,West Jordan,Utah,84084,West
cust_id-ZD-21925,Zuschuss Donatelli,Consumer,66,United States,San Francisco,California,94109,West
cust_id-KB-16585,Ken Black,Corporate,67,United States,Fremont,Nebraska,68025,Central
cust_id-SF-20065,Sandra Flanagan,Consumer,41,United States,Philadelphia,Pennsylvania,19140,East
cust_id-EB-13870,Emily Burns,Consumer,34,United States,Orem,Utah,84057,West
cust_id-EH-13945,Eric Hoffmann,Consumer,21,United States,Los Angeles,California,90049,West
cust_id-TB-21520,Tracy Blumstein,Consumer,48,United States,Philadelphia,Pennsylvania,19140,East
cust_id-MA-17560,Matt Abelman,Home Office,19,United States,Houston,Texas,77095,Central
cust_id-GH-14485,Gene Hale,Corporate,28,United States,Richardson,Texas,75080,Central
cust_id-SN-20710,Steve Nguyen,Home Office,46,United States,Houston,Texas,77041,Central
cust_id-LC-16930,Linda Cazamias,Corporate,31,United States,Naperville,Illinois,60540,Central
cust_id-RA-19885,Ruben Ausman,Corporate,51,United States,Los Angeles,California,90049,West
cust_id-ES-14080,Erin Smith,Corporate,20,United States,Melbourne,Florida,32935,South
cust_id-ON-18715,Odella Nelson,Corporate,27,United States,Eagan,Minnesota,55122,Central
cust_id-PO-18865,Patrick O'Donnell,Consumer,64,United States,Westland,Michigan,48185,Central
cust_id-LH-16900,Lena Hernandez,Consumer,66,United States,Dover,Delaware,19901,East
cust_id-DP-13000,Darren Powers,Consumer,40,United States,New Albany,Indiana,47150,Central
cust_id-JM-15265,Janet Molinari,Corporate,23,United States,New York City,New York,10024,East
cust_id-TB-21055,Ted Butterfield,Consumer,34,United States,Troy,New York,12180,East
cust_id-KM-16720,Kunst Miller,Consumer,69,United States,Los Angeles,California,90004,West
cust_id-PS-18970,Paul Stevenson,Home Office,31,United States,Chicago,Illinois,60610,Central
cust_id-BS-11590,Brendan Sweed,Corporate,45,United States,Gilbert,Arizona,85234,West
cust_id-KD-16270,Karen Daniels,Consumer,59,United States,Springfield,Virginia,22153,South
cust_id-HM-14980,Henry MacAllister,Consumer,35,United States,New York City,New York,10009,East
cust_id-JE-15745,Joel Eaton,Consumer,25,United States,Memphis,Tennessee,38109,South
cust_id-KB-16600,Ken Brennan,Corporate,29,United States,Houston,Texas,77041,Central
cust_id-SC-20770,Stewart Carmichael,Corporate,18,United States,Decatur,Alabama,35601,South
cust_id-DN-13690,Duane Noonan,Consumer,42,United States,San Francisco,California,94122,West
cust_id-JC-16105,Julie Creighton,Corporate,56,United States,Durham,North Carolina,27707,South
cust_id-CS-12400,Christopher Schild,Home Office,33,United States,Chicago,Illinois,60623,Central
cust_id-PG-18895,Paul Gonzalez,Consumer,64,United States,Rochester,Minnesota,55901,Central
cust_id-GM-14455,Gary Mitchum,Home Office,64,United States,Houston,Texas,77095,Central
cust_id-JS-15685,Jim Sink,Corporate,33,United States,Los Angeles,California,90036,West
cust_id-KB-16315,Karl Braun,Consumer,70,United States,Minneapolis,Minnesota,55407,Central
cust_id-RB-19705,Roger Barcio,Home Office,63,United States,Portland,Oregon,97206,West
cust_id-PN-18775,Parhena Norris,Home Office,35,United States,New York City,New York,10009,East
cust_id-KD-16345,Katherine Ducich,Consumer,33,United States,San Francisco,California,94122,West
cust_id-ER-13855,Elpida Rittenbach,Corporate,56,United States,Saint Paul,Minnesota,55106,Central
cust_id-RB-19465,Rick Bensley,Home Office,18,United States,Chicago,Illinois,60610,Central
cust_id-GZ-14470,Gary Zandusky,Consumer,64,United States,Rochester,Minnesota,55901,Central
cust_id-LC-16870,Lena Cacioppo,Consumer,63,United States,Aurora,Colorado,80013,West

In [14]:
cdata.describe()

             age   postal_code
count  49.000000     49.000000
mean   43.142857  59352.469388
std    17.621010  27814.913802
min    18.000000  10009.000000
25%    29.000000  35601.000000
50%    41.000000  60610.000000
75%    63.000000  84084.000000
max    70.000000  98103.000000

In [16]:
cdata.iloc[0]

customer_name      Claire Gute
segment               Consumer
age                         67
country          United States
city                 Henderson
state                 Kentucky
postal_code              42420
region                   South
Name: cust_id-CG-12520, dtype: object

In [18]:
cdata.iloc[0,5]

'Kentucky'

In [21]:
cdata.iloc[0:5]

,customer_name,segment,age,country,city,state,postal_code,region
cust_id,,,,,,,,
cust_id-CG-12520,Claire Gute,Consumer,67,United States,Henderson,Kentucky,42420,South
cust_id-DV-13045,Darrin Van Huff,Corporate,31,United States,Los Angeles,California,90036,West
cust_id-SO-20335,Sean O'Donnell,Consumer,65,United States,Fort Lauderdale,Florida,33311,South
cust_id-BH-11710,Brosina Hoffman,Consumer,20,United States,Los Angeles,California,90032,West
cust_id-AA-10480,Andrew Allen,Consumer,50,United States,Concord,North Carolina,28027,South

In [23]:
cdata.iloc[10:20]

,customer_name,segment,age,country,city,state,postal_code,region
cust_id,,,,,,,,
cust_id-KB-16585,Ken Black,Corporate,67,United States,Fremont,Nebraska,68025,Central
cust_id-SF-20065,Sandra Flanagan,Consumer,41,United States,Philadelphia,Pennsylvania,19140,East
cust_id-EB-13870,Emily Burns,Consumer,34,United States,Orem,Utah,84057,West
cust_id-EH-13945,Eric Hoffmann,Consumer,21,United States,Los Angeles,California,90049,West
cust_id-TB-21520,Tracy Blumstein,Consumer,48,United States,Philadelphia,Pennsylvania,19140,East
cust_id-MA-17560,Matt Abelman,Home Office,19,United States,Houston,Texas,77095,Central
cust_id-GH-14485,Gene Hale,Corporate,28,United States,Richardson,Texas,75080,Central
cust_id-SN-20710,Steve Nguyen,Home Office,46,United States,Houston,Texas,77041,Central
cust_id-LC-16930,Linda Cazamias,Corporate,31,United States,Naperville,Illinois,60540,Central
cust_id-RA-19885,Ruben Ausman,Corporate,51,United States,Los Angeles,California,90049,West

In [24]:
import numpy as ny

In [26]:
d1 = [{"name": 'user2',
"age": 25,
"section": 'sectionA'},
{"name": 'user5',
"age": 36,
"section": 'sectionB'}]

In [27]:
pUser = pd.DataFrame([
{"name": 'user2',
"age": 25,
"section": 'sectionA'},
{"name": 'user5',
"age": 36,
"section": 'sectionB'}])

In [28]:
pUser

    name  age   section
0  user2   25  sectionA
1  user5   36  sectionB

In [32]:
pUser.to_csv('user.csv', index= 0)

In [38]:
section = [{"section_name": 'secitonA',
"address": 'ad1',
"no_of_student": 65,},
{"section_name": 'secitonB',
"address": 'ad2',
"no_of_student": 35,}]

In [39]:
pSection = pd.DataFrame(section)

In [40]:
pSection

  section_name address  no_of_student
0     secitonA     ad1             65
1     secitonB     ad2             35